### PR TITLE
Fix borrowed_box lint for Box<Any>

### LINKED ISSUE #1884: `borrowed_box` lint and `Any`
I'm not sure that this is an issue, but it can be a little confusing.

I have the following situation: there is a function that works with `panic::catch_unwind` error (`Box<Any + Send + 'static>`):
```rust
fn foo(e: &Box<Any + Send>) {
    if let Some(s) = e.as_ref().downcast_ref::<&str>() { ... }
    ...
}
```
Clippy suggests the following:
```rust
warning: you seem to be trying to use `&Box<T>`. Consider using just `&T`
 --> src/main.rs:4:11
  |
4 | fn foo(e: &Box<Any + Send>) {
  |           ^^^^^^^^^^^^^^^^ help: try `&Any + Send`
```
Functions becomes more generic, that for sure, but `Any` is a specific type: `foo` call site must be updated otherwise instead of `Any` that contains a panic error it will take `Any` that contains `Box<Any + Send>`.

Probably `borrowed_box` lint should be disabled for `Any` type?

### PR DESCRIPTION
**Pull request by DarkEld3r**
Closes #1884.

### CODE REVIEW

File: clippy_lints/src/types.rs [hunk 1]
```diff
@@ -211,6 +211,15 @@ fn check_ty(cx: &LateContext, ast_ty: &hir::Ty, is_local: bool) {
                         let PathParameters::AngleBracketedParameters(ref ab_data) = bx.parameters,
                         let [ref inner] = *ab_data.types
                     ], {
+                        if_let_chain! {[
+                            let ty::TyDynamic(binder, _) = cx.tables.node_id_to_type(ty.id).boxed_ty().sty,
```
Comment (oli-obk) [inline clippy_lints/src/types.rs]: hmm... it seems rustc doesn't store the types anymore. `node_id_to_type` seems to panic.

We could try to do the same as above:

1. destructure TyPath (if it's not a path, it can't be `Any` anyway)
2. get the `def_id` via the `qpath_def` method and the `opt_def_id` function
3. call the `match_def_path` as you are doing it below.

**Comment by oli-obk** [comment]
Note that you can run the test suite yourself locally with `cargo test`. Afterwards you'll also need to run `tests/ui/update-all-references.sh` and commit the changed `.stderr` files.

**Comment by oli-obk** [comment]
This looks good to me now. Unfortunately you need to update your compiler, there was a version bump today, so it's best if you rebase over the master branch, too.
All that your code needs is changing the `.id` to `.hir_id` in order to work on the newest nightly

**Comment by oli-obk** [comment]
It doesn't seem to work. Can you do some println debugging to see what's actually inside `inner`? Maybe we're using the wrong variant. We might need different ones for `+ Send` and similar

**Comment by DarkEld3r** [comment]
Right, sorry for the broken pull request, but I'm still on my way to understanding what is going on. I will try to check what is wrong soon.

**Comment by DarkEld3r** [comment]
I finally came to something working. :sweat_smile: Still not sure about `match_path_old`: is it OK to use that function?

**Comment by oli-obk** [comment]
> is it OK to use that function?

Yea it's just badly named. We should name it `match_path` after renaming the current `match_path` to `match_qpath`.

The code looks good to me now. Let's see if we made travis happy.

**Comment by oli-obk** [comment]
Looks like Travis is happy indeed. Thanks for the fix and the thorough tests
