### PR TITLE
Lint for creation of invalid references

### LINKED ISSUE #2028: Lint the creation of invalid references
```rust
    let fake: &T = std::mem::zeroed();
```

Could be something a C/C++ developer considers correct if they don't know about Rust's (arguably unspecified) memory model (https://stackoverflow.com/questions/46084797/why-is-pointer-arithmetic-the-cause-of-a-segfault).

I think the only way references should be created in unsafe code is from dereferencing raw pointers.

We should probably lint calls to `std::mem::zeroed()` or `std::mem::uninitialized()`, the core variants or the `uninitialized` or `init` intrinsics.

### PR DESCRIPTION
**Pull request by lpesk**
Check for assignments to references of std::mem::zeroed(), core::mem::zeroed(), std::intrinsics::init(), std::mem::uninitialized(), core::mem::uninitialized(), and std::intrinsics::uninit(). 

fixes #2028

### CODE REVIEW

File: clippy_lints/src/invalid_ref.rs [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    fn get_lints(&self) -> LintArray {
+        lint_array!(INVALID_REF)
+    }
+}
+
+impl<'a, 'tcx> LateLintPass<'a, 'tcx> for InvalidRef {
+    fn check_expr(&mut self, cx: &LateContext<'a, 'tcx>, expr: &'tcx Expr) {
+        if_let_chain!{[
+            let ty::TyRef(..) = cx.tables.expr_ty(expr).sty,
+            let ExprCall(ref path, ref args) = expr.node,
```
Comment (Manishearth) [inline clippy_lints/src/invalid_ref.rs]: can we have the exprcall/exprpath/argument length checks first? I know it's not the logical way of looking at it, but these are less expensive so we won't be doing an expr_ty (which is a cache miss) on each expr.

File: clippy_lints/src/invalid_ref.rs [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+            let ExprPath(ref qpath) = path.node,
+            args.len() == 0,
+            let Some(def_id) = opt_def_id(cx.tables.qpath_def(qpath, path.hir_id)),
+        ], {
+            let help = "Creation of a null reference is undefined behavior; see https://doc.rust-lang.org/reference/behavior-considered-undefined.html";
```
Comment (Manishearth) [inline clippy_lints/src/invalid_ref.rs]: put this in a const up top too

File: clippy_lints/src/invalid_ref.rs [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+            let ExprPath(ref qpath) = path.node,
+            args.len() == 0,
+            let Some(def_id) = opt_def_id(cx.tables.qpath_def(qpath, path.hir_id)),
+        ], {
+            let help = "Creation of a null reference is undefined behavior; see https://doc.rust-lang.org/reference/behavior-considered-undefined.html"; 
+            if match_def_path(cx.tcx, def_id, &paths::MEM_ZEROED) | match_def_path(cx.tcx, def_id, &paths::INIT) {
+                let lint = INVALID_REF;
+                let msg = ZERO_REF_SUMMARY;
+                span_help_and_lint(cx, lint, expr.span, &msg, &help);
+            } else if match_def_path(cx.tcx, def_id, &paths::MEM_UNINIT) | match_def_path(cx.tcx, def_id, &paths::UNINIT) {
```
Comment (Manishearth) [inline clippy_lints/src/invalid_ref.rs]: Better written as:

```rust
let msg = if .... {
     ZERO_REF_SUMMARY
} else if ... {
    UNINIT_REF_SUMMARY
} else {
    return;
}
span_help_and_lint(cx, INVALID_REF, expr.span, msg, help);
```

File: clippy_lints/src/invalid_ref.rs [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+                let lint = INVALID_REF;
+                let msg = UNINIT_REF_SUMMARY;
+                span_help_and_lint(cx, lint, expr.span, &msg, &help);
```
Comment (Manishearth) [inline clippy_lints/src/invalid_ref.rs]: FWIW `msg` is already an `&str`, there's no reason to take another reference. Rust will notice this and fix it itself however, so it still works.

Clippy still warns on this though so when you run the dogfood test (`cargo test dogfood`, or just `cargo test` and wait till the end) it will probably cause an error.

File: tests/ui/invalid_ref.rs [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+    let ref_uninit: &T = std::mem::uninitialized();   // warning
+}
+
+unsafe fn ref_to_uninit_core<T: ?Sized>(t: &T) {
+    let ref_uninit: &T = core::mem::uninitialized();   // warning
+}
+
+unsafe fn ref_to_uninit_intr<T: ?Sized>(t: &T) {
+    let ref_uninit: &T = std::intrinsics::uninit();   // warning
+}
```
Comment (Manishearth) [inline tests/ui/invalid_ref.rs]: There should be tests for false positives, e.g. for a call to mem::uninitialized that is _not_ set to a reference, and for the setting of a reference that does not use any of these unsafe functions, so that the warning doesn't accidentally hit more things

**Comment by oli-obk** [comment]
🎉
