### PR TITLE
Expand on misrefactored_assign_op known problems

### LINKED ISSUE #2905: misrefactored_assign_op wrong suggestion
On this code:

```
#[allow(unused_assignments)]
fn main() {
    let mut x = 3;
    x *= 4 * x * x;
}
```

Clippy gives:

```
warning: variable appears on both sides of an assignment operation       ] 0/1: foo1
 --> src\main.rs:4:5
  |
4 |     x *= 4 * x * x;
  |     ^^^^^^^^^^^^^^
  |
  = note: #[warn(misrefactored_assign_op)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#misrefactored_assign_op
help: Did you mean x = x * 4 * x or x = x * 4 * x * x? Consider replacing it with
  |
4 |     x *= 4 * x;
  |     ^^^^^^^^^^
help: or
  |
4 |     x = x * 4 * x * x;
  |     ^^^^^^^^^^^^^^^^^
```

But `x *= 4 * x;` is a wrong suggestion because at the end x is 36 instead of 108.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #2905

@flip1995 WDYT?

### CODE REVIEW

File: clippy_lints/src/assign_ops.rs [hunk 1]
```diff
@@ -51,8 +51,10 @@ declare_clippy_lint! {
 /// **Why is this bad?** Most likely these are bugs where one meant to write `a
 /// op= b`.
 ///
-/// **Known problems:** Someone might actually mean `a op= a op b`, but that
-/// should rather be written as `a = (2 * a) op b` where applicable.
+/// **Known problems:** Clippy cannot know for sure if `a op= a op b` should have
+/// been `a = a op a op b` or `a = a op b`/`a op= b`. Therefore it suggests both.
+/// If `a op= a op b` is really the correct behaviour then
+/// rewrite it as `a = (2 * a) op b` as it's less confusing.
```
Comment (flip1995) [inline clippy_lints/src/assign_ops.rs]: I think I came up with `a = (2 * a) op b` and don't like it anymore :smile: Would be better to write this as `a = a op a op b`, I think.

Maybe formulate the second part a little different:

> If `a op= a op b` is really the correct behaviour it should be written as `a = a op a op b` as it's less confusing.

That sounds less like a suggestion, that you would expect in an error message and more like the thought behind this lint.
