### PR TITLE
Fix SpanlessHash and SpanlessEq tables

### LINKED ISSUE #1782: Panic during linting involving complicated `match` statements
I've encountered an error when linting my project resulting in a panic while compiling.  

* **Compiler Version**: rustc 1.19.0-nightly (5f3966864 2017-05-25)
* **Failing Code**: 
```rust
match Some(()) {
    Some(_) => unsafe { ptr::write(ptr::null_mut() as *mut u32, mem::transmute::<[u8; 4], _>([0, 0, 0, 255])) },
    None => unsafe { ptr::write(ptr::null_mut() as *mut u32, mem::transmute::<[u8; 4], _>([13, 246, 24, 255])) },
}
```
* **Backtrace**: https://gist.github.com/Ameobea/d57a03bf41993522bddf16afd8b69017

I've created a [PR](#1783) that includes a new test that causes a panic.  I was unable to determine the cause of the panic myself or go about fixing it, however.

### LINKED ISSUE #2499: parse_mag_decl cause clippy crash
I run "cargo +nightly clippy" for "cargo new --lib foo" crate with such `lib.rs`:

```rust
use std::str;

type ParseLineError = i32;

fn parse_num<T: str::FromStr>(s: &[u8], column: usize, len: usize) -> Result<T, ParseLineError> {
    str::from_utf8(&s[column..(column + len)])
        .map_err(|_| -1)?
        .parse::<T>()
        .map_err(|_| -1)
}

fn parse_mag_decl(s: &[u8], mut column: usize) -> Result<f64, ParseLineError> {
    let t = s[column];
    if !t.is_ascii() {
        return Err(-1);
    }
    column += 1;
    let t = t as char;
    match t {
        'E' | 'W' => {}
        'T' => if &s[column..(column + 4)] != &['0' as u8; 4] {
            return Err(-1);
        } else {
            return Ok(0.);
        },
        _ => {
            return Err(-1);
        }
    }
    let deg = parse_num::<f64>(s, column, 3)?;
    column += 3;
    let deg_tenth = parse_num::<f64>(s, column, 1)?;
    let mut val = (deg + deg_tenth / 10.).to_radians();
    if t == 'W' {
        val = -val;
    }
    Ok(val)
}
```

it crash in such way:

```
error: internal compiler error: librustc/ty/context.rs:478: node_id_to_type: no type for node `expr 4 (id=111)`

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:535:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:403
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: <std::thread::local::LocalKey<T>>::try_with
  11: <std::thread::local::LocalKey<T>>::with
  12: rustc::ty::context::tls::with
  13: rustc::ty::context::tls::with_opt
  14: rustc::session::opt_span_bug_fmt
  15: rustc::session::bug_fmt
  16: rustc::ty::context::TypeckTables::node_id_to_type
  17: rustc::ty::context::TypeckTables::expr_ty
  18: clippy_lints::consts::ConstEvalLateContext::expr
  19: clippy_lints::consts::constant_simple
  20: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  21: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  22: <clippy_lints::copies::CopyAndPaste as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  23: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::lint::context::LintContext<'tcx>>::with_lint_attrs
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_stmt
  25: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::lint::context::LintContext<'tcx>>::with_lint_attrs
  27: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  29: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  30: rustc::hir::intravisit::walk_item
  31: rustc::lint::context::LateContext::with_param_env
  32: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  33: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  34: rustc::lint::context::check_crate
  35: rustc::ty::context::TyCtxt::create_and_enter
  36: rustc_driver::driver::compile_input
  37: rustc_driver::run_compiler
```

```sh
$ cargo-clippy --version
0.0.187
```

cargo +nightly build works fine for this crate without any crash.

### LINKED ISSUE #2594: Clippy v0.0.191 with rustc 1.26.0-nightly (ae544ee1c 2018-03-29) causes ICE
After upgrading clippy from `0.0.190` to `0.0.191` running `cargo clippy` causes ICE:
```
error: internal compiler error: librustc/ty/context.rs:502: node_id_to_type: no type for node `expr 10 (id=678)`

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:543:9

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (ae544ee1c 2018-03-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `hyper`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details>
<summary>stack backtrace:</summary>

```
   0:     0x7fcf1e07185b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he90736f0673c5957
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fcf1e03f990 - std::sys_common::backtrace::print::h37226c664104fff7
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7fcf1e06529d - std::panicking::default_hook::{{closure}}::h5edcec13387dd2e3
                               at libstd/panicking.rs:207
   3:     0x7fcf1e064ffb - std::panicking::default_hook::ha0061cec4ea60cf2
                               at libstd/panicking.rs:223
   4:     0x7fcf1f6ca5bd - core::ops::function::Fn::call::hfbcf24185d298f84
   5:     0x7fcf1e0657e9 - std::panicking::rust_panic_with_hook::hb876ad0773f5dc16
                               at libstd/panicking.rs:403
   6:     0x7fcf1e7c81b9 - std::panicking::begin_panic::hfdbd973f621df2dd
   7:     0x7fcf1e7e22c1 - rustc_errors::Handler::bug::h736866a11c15ee86
   8:     0x7fcf1f7bb18c - rustc::session::opt_span_bug_fmt::{{closure}}::hcc5093a6222a995e
   9:     0x7fcf1f7cf7d6 - rustc::ty::context::tls::with_opt::{{closure}}::hd62838ecc802308f
  10:     0x7fcf1f76bba3 - <std::thread::local::LocalKey<T>>::try_with::h704311228a5d19f8
  11:     0x7fcf1f75d1b6 - <std::thread::local::LocalKey<T>>::with::h34f8eb870dcd7b1d
  12:     0x7fcf1f57336d - rustc::ty::context::tls::with::h3eef14127bf48d9d
  13:     0x7fcf1f573bb9 - rustc::ty::context::tls::with_opt::h94f1de73e548f839
  14:     0x7fcf1f2b9204 - rustc::session::opt_span_bug_fmt::hb400c0f2e3c74341
  15:     0x7fcf1f2b9176 - rustc::session::bug_fmt::h425f210348cf2b49
  16:     0x7fcf1f56cf67 - rustc::ty::context::TypeckTables::expr_ty::he46e1d05b3c3a315
  17:     0x563b23076a5d - clippy_lints::consts::ConstEvalLateContext::expr::ha7d48722fdbf4df3
  18:     0x563b23076485 - clippy_lints::consts::constant_simple::he6f8268459cdfbe9
  19:     0x563b230f2dc4 - clippy_lints::utils::hir_utils::SpanlessHash::hash_expr::ha908ce311f08e295
  20:     0x563b230f30be - clippy_lints::utils::hir_utils::SpanlessHash::hash_expr::ha908ce311f08e295
  21:     0x563b230f32ae - clippy_lints::utils::hir_utils::SpanlessHash::hash_expr::ha908ce311f08e295
  22:     0x563b230beb17 - <clippy_lints::copies::CopyAndPaste as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr::hfe6d820beccd7003
  23:     0x7fcf1f78f962 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::he3c6cf91cbf47310
  24:     0x7fcf1f791d0a - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::h1549a375ec49914c
  25:     0x7fcf1f78fa4c - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::he3c6cf91cbf47310
  26:     0x7fcf1f78e901 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::h47b6946ecc761425
  27:     0x7fcf1f78e717 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h8c7bbb4c4a61acd9
  28:     0x7fcf1f790221 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::h4b58ef8ee757f8c0
  29:     0x7fcf1f6a45e6 - rustc::hir::intravisit::walk_impl_item::h8de7a2a1eed57e94
  30:     0x7fcf1f79355d - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item::h4e63931920bc82c8
  31:     0x7fcf1f6a5aa8 - rustc::hir::intravisit::walk_impl_item_ref::h2d7c11fb9dd56a3b
  32:     0x7fcf1f67bf2e - rustc::hir::intravisit::walk_item::h7c736e7843580351
  33:     0x7fcf1f78ee4e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::hcfa3c91da0fd72d4
  34:     0x7fcf1f79167d - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::h5ab7fd8abe3b9f59
  35:     0x7fcf1f67bd6c - rustc::hir::intravisit::walk_item::h7c736e7843580351
  36:     0x7fcf1f78ee4e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::hcfa3c91da0fd72d4
  37:     0x7fcf1f79167d - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::h5ab7fd8abe3b9f59
  38:     0x7fcf1f67bd6c - rustc::hir::intravisit::walk_item::h7c736e7843580351
  39:     0x7fcf1f78ee4e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::hcfa3c91da0fd72d4
  40:     0x7fcf1f79167d - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::h5ab7fd8abe3b9f59
  41:     0x7fcf1f67258c - rustc::hir::intravisit::walk_crate::h6cd18ca6d6e4862f
  42:     0x7fcf1f798d73 - rustc::lint::context::check_crate::h9af507c9f1d2c5ec
  43:     0x7fcf205a7b99 - <std::thread::local::LocalKey<T>>::with::h4c767a532ca41fa3
  44:     0x7fcf205ae136 - <std::thread::local::LocalKey<T>>::with::he47cefd74ff28307
  45:     0x7fcf2062459e - rustc::ty::context::TyCtxt::create_and_enter::hd599c2d32b176ac6
  46:     0x7fcf20521c37 - rustc_driver::driver::compile_input::hd12ba23060796bfe
  47:     0x7fcf205d6adf - rustc_driver::run_compiler_impl::h8ab3a92625df6f67
  48:     0x7fcf204fbb18 - syntax::with_globals::h5b93a0cb73c64078
  49:     0x7fcf205d5aaf - rustc_driver::run_compiler::hcca503a25e28737c
  50:     0x563b23043fde - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1b300b01f7b087
  51:     0x563b2304c30b - std::panicking::try::do_call::hde6ee9333deb8640
  52:     0x7fcf1e07febe - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  53:     0x563b230486bd - <F as alloc::boxed::FnBox<A>>::call_box::hb74aeb5108e29d71
  54:     0x7fcf1e076f47 - std::sys_common::thread::start_thread::h5801fa5836ace044
                               at /checkout/src/liballoc/boxed.rs:793
                               at libstd/sys_common/thread.rs:24
  55:     0x7fcf1e045fb8 - std::sys::unix::thread::Thread::new::thread_start::h9ffd4ead1288775a
                               at libstd/sys/unix/thread.rs:90
  56:     0x7fcf1ddd108b - start_thread
  57:     0x7fcf1d8f1e7e - __GI___clone
  58:                0x0 - <unknown>
error: aborting due to previous error
```
</details>

Couldn't manage to reproduce it by anything different than `cargo clippy`.

Is this rustc or clippy bug (please close this issue if former)?

### LINKED ISSUE #2767: clippy triggers ICE: librustc/ty/context.rs:527: node_id_to_type: no type for node `expr 10 (id=678)`
This happens on current Askama master, clippy 0.0.200 and rustc 1.27.0-nightly (f0fdaba04 2018-05-15).

```
thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:554:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::bug_fmt
  14: rustc::ty::context::TypeckTables::expr_ty
  15: clippy_lints::consts::ConstEvalLateContext::expr
  16: clippy_lints::consts::constant_simple
  17: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  18: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  19: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  20: <clippy_lints::copies::CopyAndPaste as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  21: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  23: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  25: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  27: rustc::hir::intravisit::walk_impl_item
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  29: rustc::hir::intravisit::walk_impl_item_ref
  30: rustc::hir::intravisit::walk_item
  31: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  32: rustc::hir::intravisit::walk_mod
  33: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  34: rustc::hir::intravisit::walk_item
  35: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  36: rustc::hir::intravisit::walk_mod
  37: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  38: rustc::hir::intravisit::walk_item
  39: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  40: rustc::hir::intravisit::walk_mod
  41: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  42: rustc::lint::context::check_crate
  43: rustc::util::common::time
  44: rustc::ty::context::tls::enter_context
  45: <std::thread::local::LocalKey<T>>::with
  46: rustc::ty::context::TyCtxt::create_and_enter
  47: rustc_driver::driver::compile_input
  48: rustc_driver::run_compiler_with_pool
  49: <scoped_tls::ScopedKey<T>>::set
  50: syntax::with_globals
  51: rustc_driver::run_compiler
  52: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  53: std::panicking::try::do_call
  54: __rust_maybe_catch_panic
  55: rustc_driver::run
  56: clippy_driver::main
  57: std::rt::lang_start::{{closure}}
  58: std::panicking::try::do_call
  59: __rust_maybe_catch_panic
  60: std::rt::lang_start_internal
  61: main
query stack during panic:
end of query stack
```

### PR DESCRIPTION
**Pull request by phansch**
This makes sure the correct tables are used for constant lookup around `SpanlessHash` and `SpanlessEq`

Fixes #2767 
Fixes #2594 
Fixes #2499 
Closes #1783
Fixes #1782

### CODE REVIEW

**Comment by oli-obk** [comment]
> is in a different body table for some reason:

Oh, it's in a different body table because it's a constant ;). The expression variant (ExprRepeat) has a field of type BodyId. Try calling `cx.tcx.body_tables(id)` with said id to obtain the correct table

**Comment by phansch** [comment]
Thanks! The code slowly starts to make sense to me :eyes: 

https://github.com/rust-lang-nursery/rust-clippy/pull/2763/commits/8fdf2a8f77c8a3e8bed247bc21d0bc77f55a221b#diff-facf8838686f92b7be75999cfbe7e987R493 fixes the SpanlessHash ICE. However it feels not correct to me, because it will set the table to the table of the constant for the following iterations, which could potentially cause other lookup issues.

And actually it *does* change the debug output for `run-pass/ice-2499` that shows that now the table has been changed to the table that contains the constants and any non-constant item lookup fails :/

File: clippy_lints/src/utils/hir_utils.rs [hunk 1]
```diff
@@ -490,6 +490,7 @@ impl<'a, 'tcx: 'a> SpanlessHash<'a, 'tcx> {
                 let c: fn(_, _) -> _ = ExprRepeat;
                 c.hash(&mut self.s);
                 self.hash_expr(e);
+                self.tables = self.cx.tcx.body_tables(l_id);
                 self.hash_expr(&self.cx.tcx.hir.body(l_id).value);
```
Comment (oli-obk) [inline clippy_lints/src/utils/hir_utils.rs]: You can store the old tables in a temporary variable and restore them afterwards. This is essentially how rustc does it for `LateContext`. We should probably abstract that feature in some generic form so all the cases where we or rustc do it can be made correct in a way that can't be accidentally forgotten.

**Comment by phansch** [comment]
Ok, I think this is ready for review @oli-obk

**Comment by Ameobea** [comment]
Thanks very much for this!
