### PR TITLE
Fix #1159: avoid comparing fixed and target sized types in lint

### LINKED ISSUE #1159: Spurious `absurd_extreme_comparisons` involving `usize`
```
fn too_big_for_memory(len: u64) -> bool {
    len >= std::usize::MAX as u64
}
```

spuriously triggers `absurd_extreme_comparisons` with a 64-bit target (I assume it doesn't for other bitsizes, but I don't have an easy way to check). I'd be nice for `std::usize::MAX` to not evaluate to a constant in this case.

### PR DESCRIPTION
**Pull request by kimsnj**
PR to fix #1159

### CODE REVIEW

**Comment by oli-obk** [comment]
Thanks!

File: clippy_lints/src/types.rs [hunk 1]
```diff
@@ -1106,6 +1106,20 @@ enum AbsurdComparisonResult {
...
+fn is_cast_between_fixed_and_target<'a, 'tcx>(
+    cx: &LateContext<'a, 'tcx>,
+    expr: &'tcx Expr
+) -> bool {
+
+    if let ExprCast(ref cast_exp, _) = expr.node {
+        let precast_ty = cx.tables.expr_ty(cast_exp);
+        let cast_ty = cx.tables.expr_ty(expr);
+
+        return is_isize_or_usize(precast_ty) != is_isize_or_usize(cast_ty)
```
Comment (oli-obk) [inline clippy_lints/src/types.rs]: neat trick
