### PR TITLE
Fix #2160

### LINKED ISSUE #2160: Clippy crashing on galvanic_test fixture
I get a panic from clippy. How to reproduce:

* `cargo new --bin cli-crash`
* Add `galvanic-test = "~0.1"` as a dependency (it is currently 0.1.3).
* Put this into `tests/t.rs`:

```rust
#[macro_use]
extern crate galvanic_test;

test_suite! {
    fixture f() -> () {
        setup(&mut self) { }
    }
}
```
* Run cargo clippy.

The relevant versions:
```
rustc 1.22.0-nightly (4750c1ec0 2017-10-19)
binary: rustc
commit-hash: 4750c1ec047f18bc0e33823182e09711a3826fb5
commit-date: 2017-10-19
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0

$ cargo-clippy --version
0.0.166
```

This is the backtrace I get:

```
$ cargo clippy
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Compiling cli-crash v0.1.0 (file:///home/vorner/cli-crash)
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /checkout/src/liballoc/vec.rs:1553:10
stack backtrace:
   0:     0x7fa1d70ab033 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1a7fed0b88218a4c
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fa1d70a5760 - std::sys_common::backtrace::_print::h9aefda753d3f4839
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
   2:     0x7fa1d70b8533 - std::panicking::default_hook::{{closure}}::hd3ce94b04f725363
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7fa1d70b82a2 - std::panicking::default_hook::h74cae8024f14a070
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7fa1d70b89f7 - std::panicking::rust_panic_with_hook::hc90d8ce746f2ebef
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7fa1d70b8854 - std::panicking::begin_panic::h44442df5cfbb0822
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7fa1d70b87c9 - std::panicking::begin_panic_fmt::h0e39672547129679
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7fa1d70b875a - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x7fa1d7112650 - core::panicking::panic_fmt::hde1a1a3fb45329c1
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x7fa1d71125f8 - core::panicking::panic_bounds_check::hf2eec6138f23b5a6
                               at /checkout/src/libcore/panicking.rs:58
  10:     0x55e7ef119863 - clippy_lints::is_unit_expr::is_unit_expr::hd891726ce85b4e85
  11:     0x55e7ef1196c4 - <clippy_lints::is_unit_expr::UnitExpr as rustc::lint::EarlyLintPass>::check_stmt::h33ea883563e914b3
  12:     0x7fa1d83d6f1c - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_stmt::h62e6d1bed802d0ff
  13:     0x7fa1d83d89de - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_block::h1a034911ec590875
  14:     0x7fa1d83d7322 - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_fn::h162ca8f9f33430ce
  15:     0x7fa1d83d98a9 - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_impl_item::{{closure}}::h9791737d587e1307
  16:     0x7fa1d83d1e6a - <rustc::lint::context::EarlyContext<'a> as rustc::lint::context::LintContext<'a>>::with_lint_attrs::hfc408d761c2b87a1
  17:     0x7fa1d83d8503 - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod::h4874481eace1b0fd
  18:     0x7fa1d83d2256 - <rustc::lint::context::EarlyContext<'a> as rustc::lint::context::LintContext<'a>>::with_lint_attrs::hfc408d761c2b87a1
  19:     0x7fa1d83d8503 - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod::h4874481eace1b0fd
  20:     0x7fa1d83dab87 - rustc::lint::context::check_ast_crate::h01161f2387515ac5
  21:     0x7fa1d92db8dd - rustc_driver::driver::phase_2_configure_and_expand::heef7b0bf42617f9c
  22:     0x7fa1d92d2bd6 - rustc_driver::driver::compile_input::h0bcd39d2d85ad71c
  23:     0x7fa1d92f13ae - rustc_driver::run_compiler::hb441b7c139679aa6
  24:     0x55e7ef034c76 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd040f82cefd59f83
  25:     0x55e7ef0353ed - std::panicking::try::do_call::hd523c72d339d5c62
  26:     0x7fa1d7101e9c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  27:     0x55e7ef03a512 - <F as alloc::boxed::FnBox<A>>::call_box::hf47c29543e3b5be4
  28:     0x7fa1d70b73fb - std::sys::imp::thread::Thread::new::thread_start::h7c4d175e4fb224c5
                               at /checkout/src/liballoc/boxed.rs:772
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  29:     0x7fa1d6e22856 - <unknown>
  30:     0x7fa1d664312e - __clone
  31:                0x0 - <unknown>
thread 'main' panicked at 'rustc_thread failed: Any', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0:     0x7fa1d70ab033 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1a7fed0b88218a4c
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fa1d70a5760 - std::sys_common::backtrace::_print::h9aefda753d3f4839
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
   2:     0x7fa1d70b8533 - std::panicking::default_hook::{{closure}}::hd3ce94b04f725363
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7fa1d70b82a2 - std::panicking::default_hook::h74cae8024f14a070
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7fa1d70b89f7 - std::panicking::rust_panic_with_hook::hc90d8ce746f2ebef
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7fa1d70b8854 - std::panicking::begin_panic::h44442df5cfbb0822
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7fa1d70b87c9 - std::panicking::begin_panic_fmt::h0e39672547129679
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7fa1d70b875a - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x7fa1d7112650 - core::panicking::panic_fmt::hde1a1a3fb45329c1
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x55e7ef03a44e - core::result::unwrap_failed::haa49d6c4ead23266
  10:     0x55e7ef03bbad - clippy_driver::main::h69709da3db18b2d4
  11:     0x7fa1d7101e9c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  12:     0x7fa1d70b995b - std::rt::lang_start::h12a9dbbd0e21bb7d
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  13:     0x7fa1d656b530 - __libc_start_main
  14:     0x55e7ef0335b9 - _start
  15:                0x0 - <unknown>
error: Could not compile `cli-crash`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by HMPerson1**
I don't think there's a point to linting `let x = {};`; it's extremely unlikely to be a mistake.

### CODE REVIEW

**Comment by llogiq** [comment]
I'd still like to discuss your rationale. Why do you think this is no mistake? `x` will be bound to `()`, which is unlikely to be useful.

**Comment by HMPerson1** [comment]
I agree that binding anything to `()` is unlikely to be useful, but it's not likely that someone would write 

```rust
let x = {};
```

intending something else in the same way that someone writing

```rust
let x = {
   foo();
   bar(); // with semicolon
}
```

almost certainly intended

```rust
let x = {
   foo();
   bar() // no semicolon
}
```

I guess it still might be useful to lint, but that would require a bit of refactoring as the current code for the lint assumes that all unit expressions result from semicolons.

File: clippy_lints/src/is_unit_expr.rs [hunk 1]
```diff
@@ -132,6 +132,7 @@ fn is_unit_expr(expr: &Expr) -> Option<Span> {
 }
 
 fn check_last_stmt_in_block(block: &Block) -> bool {
+    if block.stmts.is_empty() { return false; }
```
Comment (oli-obk) [inline clippy_lints/src/is_unit_expr.rs]: Can't you just return `true` and it'll report the `{}`? If the error message doesn't match, you can create an enum (Ignore, Semi, EmptyBlock) and return that here.

**Comment by oli-obk** [comment]
ping @HMPerson1

**Comment by oli-obk** [comment]
Thanks
