### PR TITLE
Don't lint range syntax with var name `start` and/or `end`

### LINKED ISSUE #2491: `redundant_field_names` with ranges
[Playground](https://play.rust-lang.org/?gist=593cbb20b90db6dd90708d08902b1ffb&version=nightly)

Clippy suggests replacing variable `start` with `start` and `end` with `end` used in range syntax.
I guess that is because the syntax is syntactic sugar and structs resulting from desugaring have fields with these names.
IMHO we should make an exception to treat these range syntax.

```rust
warning: redundant field names in struct initialization
 --> src/main.rs:3:13
  |
3 |     let _ = start..;
  |             ^^^^^ help: replace it with: `start`
  |
  = note: #[warn(redundant_field_names)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#redundant_field_names

warning: redundant field names in struct initialization
 --> src/main.rs:6:15
  |
6 |     let _ = ..end;
  |               ^^^ help: replace it with: `end`
  |
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#redundant_field_names

warning: redundant field names in struct initialization
 --> src/main.rs:8:13
  |
8 |     let _ = start..end;
  |             ^^^^^ help: replace it with: `start`
  |
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#redundant_field_names

warning: redundant field names in struct initialization
 --> src/main.rs:8:20
  |
8 |     let _ = start..end;
  |                    ^^^ help: replace it with: `end`
  |
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#redundant_field_names
```

### PR DESCRIPTION
**Pull request by ordovicia**
Fixes #2491.

But this PR introduces new false-negative:
does not lint hand-written `Range` struct family with var name `start` and/or `end`,
i.e. `std::ops::Range { start: start, end: end }`
But I guess it's rare to write them explicitly.

### CODE REVIEW

File: clippy_lints/src/redundant_field_names.rs [hunk 1]
```diff
@@ -36,10 +38,14 @@ impl LintPass for RedundantFieldNames {
 
 impl<'a, 'tcx> LateLintPass<'a, 'tcx> for RedundantFieldNames {
     fn check_expr(&mut self, cx: &LateContext<'a, 'tcx>, expr: &'tcx Expr) {
-        if let ExprStruct(_, ref fields, _) = expr.node {
+        if let ExprStruct(ref path, ref fields, _) = expr.node {
```
Comment (oli-obk) [inline clippy_lints/src/redundant_field_names.rs]: Have you tried checking with the `in_macro` method? I think this should have expansion info, so we should be able to detect it that way

Comment (ordovicia) [reply clippy_lints/src/redundant_field_names.rs]: I didn't know `in_macro()` until now.
But the method intends not to treat range expressions as "in_macro" (since #1373).

https://github.com/rust-lang-nursery/rust-clippy/blob/598acba7d5561b2096dfa72a39247983852b9bea/clippy_lints/src/utils/mod.rs#L56-L65

So I've added a method which determines whether an expression is a range expression.
Now range expressions are ignored, and hand-written `Range` family structs are treated normally by the lint.

Comment (oli-obk) [reply clippy_lints/src/redundant_field_names.rs]: nice! The diff lgtm. Let's wait for travis and then merge
