### PR TITLE
Rust upgrade to rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)

### LINKED ISSUE #2089: Fails to build with: rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)
```
error[E0408]: variable `DotDotDot` is not bound in all patterns
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.164/src/utils/sugg.rs:365:9
    |
365 |         DotDot | DotDotDot => Associativity::None,
    |         ^^^^^^   --------- variable not in all patterns
    |         |
    |         pattern doesn't bind `DotDotDot`
error[E0599]: no associated item named `DotDotDot` found for type `syntax::util::parser::AssocOp` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.164/src/utils/sugg.rs:129:74
    |
129 |             ast::ExprKind::Range(.., RangeLimits::Closed) => Sugg::BinOp(AssocOp::DotDotDot, snippet),
    |                                                                          ^^^^^^^^^^^^^^^^^^
error[E0599]: no associated item named `DotDotDot` found for type `syntax::util::parser::AssocOp` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.164/src/utils/sugg.rs:168:52
    |
168 |             ast::RangeLimits::Closed => make_assoc(AssocOp::DotDotDot, &self, &end),
    |                                                    ^^^^^^^^^^^^^^^^^^
error[E0599]: no associated item named `DotDotDot` found for type `syntax::util::parser::AssocOp` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.164/src/utils/sugg.rs:315:9
    |
315 |         AssocOp::DotDotDot => format!("{}...{}", lhs, rhs),
    |         ^^^^^^^^^^^^^^^^^^
error: aborting due to 4 previous errors
error: Could not compile `clippy_lints`.
```

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #2089

### CODE REVIEW

File: clippy_lints/src/utils/sugg.rs [hunk 1]
```diff
@@ -312,7 +312,7 @@ pub fn make_assoc(op: AssocOp, lhs: &Sugg, rhs: &Sugg) -> Sugg<'static> {
         AssocOp::AssignOp(op) => format!("{} {}= {}", lhs, token_to_string(&token::BinOp(op)), rhs),
         AssocOp::As => format!("{} as {}", lhs, rhs),
         AssocOp::DotDot => format!("{}..{}", lhs, rhs),
-        AssocOp::DotDotDot => format!("{}...{}", lhs, rhs),
+        AssocOp::DotDotEq => format!("{}...{}", lhs, rhs),
```
Comment (Aaron1011) [inline clippy_lints/src/utils/sugg.rs]: Should this be changed to `..=`?

Comment (Manishearth) [reply clippy_lints/src/utils/sugg.rs]: yeah, that's why it's not landed yet, i need to do this

Comment (Manishearth) [reply clippy_lints/src/utils/sugg.rs]: (bit busy atm)
