### PR TITLE
Fix let_unit_value with for loop iterating over units

### LINKED ISSUE #1964: let_unit_value false warning on for _ in std::sync::mpsc::Receiver::iter()
[Playground example](https://play.rust-lang.org/?gist=7f440909eaf482e5c4279bd31120ec3f&version=stable) with the main point being this:

```
let rx: ::std::sync::mpsc::Receiver<()> = rx;

for _ in rx.iter() {
    // anything
}
```

Todays playground and the clippy version I have installed (0.0.150) both report:

```
warning: this let-binding has unit value. Consider omitting `let for _ in rx.iter() {
            count += 1;
        } =`
  --> src/main.rs:10:9
   |
10 | /         for _ in rx.iter() {
11 | |             count += 1;
12 | |         }
   | |_________^
   |
   = note: #[warn(let_unit_value)] on by default
   = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#let_unit_value

warning: this let-binding has unit value. Consider omitting `let _ =`
  --> src/main.rs:10:9
   |
10 | /         for _ in rx.iter() {
11 | |             count += 1;
12 | |         }
   | |_________^
   |
   = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#let_unit_value
```

I don't think there is duplicate of this reported. `let_unit_value` related found:

 * #1502 in the context of `let _: () = ...` but not in for loop
 * #164 mentions in context of derives

My real use case for using `Receiver<()>` is to provide a way for a worker thread to sleep with notifications. I guess this could be implemented in other ways but this was a quick solution that seems to work. `std::thread::Thread` might even provide a better way for this via `park()` and `unpark()`.

### PR DESCRIPTION
**Pull request by koivunej**
This will fix #1964, which simplifies to the code below getting lint `let_unit_value`:

```
for _ in &[()] {
  // anything
}
```

Fix is to modify `is_from_for_desugar` to detect HIR-level `let _ = for _ in ... {}` in addition to the previously detected HIR-level `let _ = for something in ... {}`. Also adds comments to explain the previous desugaring detection.

Does not add the test case suggested by @oli-obk:
> Also add an example that would have triggered if the first if_let_chain were removed, so we don't have to hope dogfood will catch it but have an explicit test in the suite.

I did not add a new case because commenting out the first check (and disabling `tests/dogfood.rs`) will cause a large number of `tests/ui/for_loop.rs` to receive `for_let_unit` lints such as:

```
error: this let-binding has unit value. Consider omitting `let for _v in hm.iter() { } =`
   --> $DIR/for_loop.rs:234:5
    |
234 |     for _v in hm.iter() { }
    |     ^^^^^^^^^^^^^^^^^^^^^^^
```

Only ui-test changes are included as I didn't find any test cases for the `is_from_for_desugar`. I'd imagine something like the example below would be awesome but might not be possible at the moment (I don't know the rustc at all).

```
assert!(is_from_for_desugar(hir! { for _ in 0.. {} });
```

### CODE REVIEW

File: clippy_lints/src/utils/higher.rs [hunk 1]
```diff
@@ -114,13 +114,36 @@ pub fn range(expr: &hir::Expr) -> Option<Range> {
...
+    // ```
     if_let_chain! {[
         let hir::DeclLocal(ref loc) = decl.node,
         let Some(ref expr) = loc.init,
         let hir::ExprMatch(_, _, hir::MatchSource::ForLoopDesugar) = expr.node,
     ], {
         return true;
     }}
+
+    // This detects a variable binding in for loop to avoid `let_unit_value`
```
Comment (koivunej) [inline clippy_lints/src/utils/higher.rs]: > This detects a variable binding ...

Should had been something like "This detects a `_` binding ..." or "This detects an underscore binding". Latter might be more searchable or greppable?

Comment (oli-obk) [inline clippy_lints/src/utils/higher.rs]: This is fine. I think it would happen for others, too, like if you had `for Foo { a } in bar {}`

Comment (koivunej) [inline clippy_lints/src/utils/higher.rs]: Cannot see it matching this for-loop. `is_from_for_desugar` returns false for the following:

```
#![feature(plugin)]
#![plugin(clippy)]

fn main() {
    let b = vec![Foo { a: 42 }];

    for Foo { a } in b {
        println!("a: {}", a);
    }
}

struct Foo {
    a: u32
}
```

<details><summary>The `{:#?}` output of decl in above example</summary>

```
Spanned {
    node: DeclLocal(
        Local {
            pat: pat(8: b),
            ty: None,
            init: Some(
                expr(26: <[_]>::into_vec(box [Foo{a: 42,}]))
            ),
            id: NodeId(
                7
            ),
            hir_id: HirId {
                owner: DefIndex(
                    3
                ),
                local_id: ItemLocalId(
                    1
                )
            },
            span: ./example.rs:5:5: 5:32,
            attrs: ThinVec(
                None
            ),
            source: Normal
        }
    ),
    span: ./example.rs:5:5: 5:33
}
```

</details>

Comment (koivunej) [inline clippy_lints/src/utils/higher.rs]: For the previous comment I had the println!'s wrong. There are a couple of tests but the example `for Foo { a } in bar` is handled by the original check in `is_from_for_desugar`.

Comment (oli-obk) [inline clippy_lints/src/utils/higher.rs]: I think that's a different `DeclLocal` than the one we're looking for, but it should probably also contain a `source` other than `Normal`. I'll see if I can produce a PR for rustc.

I think it'll call `is_from_for_desugar` if you have a `let a = 42;` outside the for loop, which will trigger the shadowing lints.

This PR is fine as it is, since this is a non-issue for the `let_unit_value` lint anyway

**Comment by oli-obk** [comment]
Thanks! This is some great detective work you did there
