### PR TITLE
Fix #2741

### LINKED ISSUE #2741: min_max lint handles negative numbers incorrectly
The code:
```rust
    let test = 554;
    println!("{}", cmp::min(cmp::max(test, -30_000), 30_000));
```
Gives the clippy error
```
error: this min/max combination leads to constant result
 --> src/main.rs:4:20
  |
4 |     println!("{}", cmp::min(cmp::max(test, -30_000), 30_000));
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[deny(min_max)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.195/index.html#min_max
```
Yet running the code will produce the correct output. Changing the `-30_000` to `0` makes the clippy error stop.

Playground example: http://play.rust-lang.org/?gist=b365f1fc9b521abbeb05fbace8fb5b45&version=stable&mode=debug

### PR DESCRIPTION
**Pull request by mikerite**

### CODE REVIEW

File: clippy_lints/src/minmax.rs [hunk 1]
```diff
@@ -36,21 +37,43 @@ impl LintPass for MinMaxPass {
 impl<'a, 'tcx> LateLintPass<'a, 'tcx> for MinMaxPass {
     fn check_expr(&mut self, cx: &LateContext<'a, 'tcx>, expr: &'tcx Expr) {
         if let Some((outer_max, outer_c, oe)) = min_max(cx, expr) {
-            if let Some((inner_max, inner_c, _)) = min_max(cx, oe) {
+            if let Some((inner_max, inner_c, ie)) = min_max(cx, oe) {
                 if outer_max == inner_max {
                     return;
                 }
-                match (outer_max, outer_c.partial_cmp(&inner_c)) {
```
Comment (oli-obk) [inline clippy_lints/src/minmax.rs]: Maybe we should replace the PartialCmp impl with an impl method that also takes a type (basically your code below). Because if we are using this method in other places, they probably have the same bug

**Comment by mikerite** [comment]
I made the change to `partial_cmp`.

I was wondering whether it would be a good idea to split `Constant::Int` into a signed and unsigned variants and fold some of the `FullInt` code from `types.rs` into `constants.rs`. `Constant::Int` is the only variant that contains its bit representation and not it's value.

**Comment by oli-obk** [comment]
Yea that feels like the right thing to do. When I did that change I ran into some problems with that approach, but I don't remember what it was

**Comment by mikerite** [comment]
Sounds like an "interesting project" but I won't try it right now.

This request is ready to merge if you're OK with it.

**Comment by oli-obk** [comment]
Oh yea, that wasn't a blocker for this PR. I just forgot about it ;)
