### PR TITLE
Fix 3145

### LINKED ISSUE #3145: panic when comma missing in println!() arg
code reduced from https://github.com/rust-lang/rust/blob/master/src/test/ui/macros/missing-comma.rs
reduced code:
````rust
fn main() {
    println!("{}" a);
}
````

crashes on regular "cargo clippy" invocation

````
thread 'main' panicked at 'assertion failed: parser.eat(&token::Eof)', tools/clippy/clippy_lints/src/write.rs:281:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   6: std::panicking::begin_panic
   7: clippy_lints::write::check_tts
   8: <clippy_lints::write::Pass as rustc::lint::EarlyLintPass>::check_mac
   9: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mac
  10: syntax::visit::walk_stmt
  11: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_block
  12: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_fn
  13: syntax::visit::walk_item
  14: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item
  15: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod
  16: rustc::lint::context::check_ast_crate
  17: rustc::util::common::time
  18: rustc_driver::driver::phase_2_configure_and_expand
  19: rustc_driver::driver::compile_input
  20: rustc_driver::run_compiler_with_pool
  21: <scoped_tls::ScopedKey<T>>::set
  22: rustc_driver::run_compiler
  23: <scoped_tls::ScopedKey<T>>::set
  24: syntax::with_globals
  25: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  26: rustc_driver::run
  27: clippy_driver::main
  28: std::rt::lang_start::{{closure}}
  29: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  30: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  31: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  32: main
  33: __libc_start_main
  34: <unknown>
query stack during panic:
end of query stack
error: internal compiler error: unexpected panic
````

Found via https://github.com/rust-lang-nursery/rust-clippy/issues/3142

### PR DESCRIPTION
**Pull request by flip1995**
Fixes #3145

This error originates on this assert:
https://github.com/rust-lang-nursery/rust-clippy/blob/63a46b1e1a9a4cc3d78e1cf7a628421051c21167/clippy_lints/src/write.rs#L286-L289

The `check_tts` function gets the arguments of the macro call as a `ThinTokenStream`:
```rust
writeln!(v, "{}", "foo"); => ThinTokenStream <v, "{}", "foo"> 
```
The thought behind this assertion is that if no `Comma` is found after a parsed `expr` the parser has reached the end of the`ThinTokenStream`, because `expr`s need to be seperated by a `Comma`. But with a syntax error like `println!("{}" a);` this is not the case. Removing the assertion is a simple fix, that shouldn't break anything.

r? @oli-obk

### CODE REVIEW

File: tests/compile-fail/issue-3145.rs [hunk 1]
```diff
@@ -0,0 +1,3 @@
+fn main() {
+    println!("{}" a); //~ERROR expected token: `,`
```
Comment (oli-obk) [inline tests/compile-fail/issue-3145.rs]: just make it a ui test. Rustc is moving away from compile-fail, there's no guarantee these are kept around.

Comment (flip1995) [reply tests/compile-fail/issue-3145.rs]: Done
