### PR TITLE
new_ret_no_self

### LINKED ISSUE #3220: new_ret_no_self complains about new() -> impl Future<Self> if new() takes parameters
`0.0.212 (2018-09-17 125907a)`

[Playground](https://play.rust-lang.org/?gist=b9ba6a68babfe77aeb8ef34058a9b732&version=nightly&mode=debug&edition=2015)

```rust
#![feature(tool_lints)]

#![deny(clippy::new_ret_no_self)]

extern crate futures;
use futures::{Future, IntoFuture};

struct S;

impl S {
    pub fn new(_: String) -> impl Future<Item = Self, Error = ()>
    {
        Ok(S).into_future()
    }
}

fn main() {}
```

```
error: methods called `new` usually return `Self`
  --> src/main.rs:11:5
   |
11 | /     pub fn new(_: String) -> impl Future<Item = Self, Error = ()>
12 | |     {
13 | |         Ok(S).into_future()
14 | |     }
   | |_____^
   |
note: lint level defined here
  --> src/main.rs:3:9
   |
3  | #![deny(clippy::new_ret_no_self)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#new_ret_no_self
```

If `S::new()` does not have the `String` parameter, the lint does not complain.

### PR DESCRIPTION
**Pull request by JoshMcguigan**
Fixes #3220 

This adds test coverage for the `new_ret_no_self` lint, corrects the false positive reported in #3220, and corrects a false negative when the `new` function takes no arguments and doesn't return self. 

However, to correct the false positive from #3220, I am simply disabling the lint if the return type is `impl trait`. This causes a different false negative as shown in the following case.

```rust
// should trigger the lint, but currently does not
pub fn new(_: String) -> impl R<Item = u32> {
    S3
}
```

I was not able to figure out how to inspect the associated types of the returned `impl trait`, but if that is possible then we could check for the type of `self` (S3 in the example above) in the associated types and correct this false negative as well.

### CODE REVIEW

File: tests/ui/new_ret_no_self.rs [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+}
+
+struct S3;
+
+impl R for S3 {
+    type Item = u32;
+}
+
+impl S3 {
+    // should trigger the lint, but currently does not
```
Comment (oli-obk) [inline tests/ui/new_ret_no_self.rs]: You can try debug printing `ret_ty.sty`, for this case it should be `TyKind::Opaque`. If it is not, then the `return_ty` function seems to alread reveal impl trait types. If that is the case, we'll need to figure out a way to get the unadjusted signature inside the `return_ty` function

Comment (oli-obk) [reply tests/ui/new_ret_no_self.rs]: I presume you mean the concrete type that the impl trait hides. You get it by calling `cx.tcx.type_of(def_id)`.

Using the concrete type will mess up your check in https://github.com/rust-lang-nursery/rust-clippy/pull/3253/files/3da7c1013cc9c62357261e786958c479bc5c3e09#diff-76448e132e544f8a1ff89ffa05ef9566R917 though and thus create new false positives I presume

Comment (JoshMcguigan) [reply tests/ui/new_ret_no_self.rs]: `cx.tcx.type_of(def_id)` returns `S`, `S2`, and `S3` as you said. I am looking for something that would return `impl R<Item = Self>` or `impl R<Item = u32>`. 

Does that exist?

**Comment by JoshMcguigan** [comment]
I think I got it this time. All previous tests pass, and it now correctly triggers the lint for `pub fn new(_: String) -> impl R<Item = u32>` and it does not trigger for `pub fn new(_: String) -> impl Q<Item = u32, Item2 = Self>`.

That said, I am way out of my depth here and basically got this working by poking around the `rustc` API until I found something that seemed to work. Please let me know if there is anything else that could be improved.

**Comment by phansch** [comment]
It looks like Clippy contains a case where `new` returns `Option<Self>` and our dogfood test [fails](https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/437447649#L1397) on travis:

https://github.com/rust-lang-nursery/rust-clippy/blob/d47dbf598adc4a6407ea34b44399907cb068d7a9/clippy_lints/src/types.rs#L1922

I'm not really sure what this `new` method does, so I guess the easiest way would be to just add an `allow` for this one method.

**Comment by JoshMcguigan** [comment]
Hopefully that takes care of it. I did a rebase as well.

**Comment by JoshMcguigan** [comment]
Rebased again. Let me know if you see any other issues with this.

**Comment by oli-obk** [comment]
Thanks! Lgtm now
