### PR TITLE
Fix false positive in empty_line_after_outer_attr

### LINKED ISSUE #2583: empty_line_after_outer_attr false positive with block comments
For the following code:
```rust
#[cfg(any(target_pointer_width = "32", target_pointer_width = "64"))]
/*

*/
pub struct S;
```
clippy 0.0.190 produces the following warning:
```
warning: Found an empty line after an outer attribute. Perhaps you forgot to add a '!' to make it an inner attribute?
 --> src/lib.rs:1:1
  |
1 | / #[cfg(any(target_pointer_width = "32", target_pointer_width = "64"))]
2 | | /*
3 | |
4 | | */
5 | | pub struct S;
  | |_
  |
  = note: #[warn(empty_line_after_outer_attr)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.190/index.html#empty_line_after_outer_attr
```

This false positive is not triggered when the attribute is `derive` rather than `cfg`, or if the item is a function rather than a struct.

### PR DESCRIPTION
**Pull request by phansch**
Before, when you had a block comment between an attribute and the
following item like this:

```rust
#[crate_type = "lib"]
/*

*/
pub struct Rust;
```

It would cause a false positive on the lint, because there is an empty
line inside the block comment.

This makes sure that basic block comments are detected and removed from
the snippet that was created before.

Fixes #2583

### CODE REVIEW

**Comment by CAD97** [comment]
I think a single line block comment will break this...?

File: clippy_lints/src/utils/mod.rs [hunk 1]
```diff
@@ -1086,3 +1086,37 @@ pub fn clip(tcx: TyCtxt, u: u128, ity: ast::UintTy) -> u128 {
...
+/// // => vec![]
+///
+/// without_block_comments(vec!["bar", "/*", "foo", "*/"]);
+/// // => vec!["bar"]
+/// ```
+pub fn without_block_comments(lines: Vec<&str>) -> Vec<&str> {
+    let mut without = vec![];
+
+    // naive approach for block comments
+    let mut inside_comment = false;
```
Comment (oli-obk) [inline clippy_lints/src/utils/mod.rs]: I think this needs to be a counter, because in rust you can nest block comments

**Comment by oli-obk** [comment]
We should probably move this lint to the nursery group for now.

**Comment by phansch** [comment]
I fully agree about moving it to the nursery :+1: 

@CAD97 I couldn't break with a single line block comment. I added an additional test for 

```rust
#[crate_type = "lib"]
/* test */
pub struct T;
```
which doesn't break it. Did you have something else in mind?
