### PR TITLE
Fix string_lit_as_bytes lint for macros

### LINKED ISSUE #3205: Wrong suggestion for `string_lit_as_bytes` lint
Error Message:

```
warning: calling `as_bytes()` on a string literal
  --> plot/src/lib.rs:40:25
   |
40 |         stdin.write_all(include_str!("./percentage_stacked_area_chart.py").as_bytes())?;
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a byte string literal instead: `binclude_str!("./percentage_stacked_area_chart.py")`
   |
   = note: #[warn(clippy::string_lit_as_bytes)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#string_lit_as_bytes
```

`stdin` is the stdin handle of a child process which I want to communicate with.

The suggestion to use `binclude_str!` is wrong, as this macro does not exist. The correct solution would be to suggest `include_bytes!`.

Clippy version:
clippy 0.0.212 (125907a 2018-09-17)

### PR DESCRIPTION
**Pull request by yaahallo**
Prior to this change, string_lit_as_bytes would trigger for constructs
like `include_str!("filename").as_bytes()` and would recommend fixing it
by rewriting as `binclude_str!("filename")`.

This change updates the lint to act as an EarlyLintPass lint. It then
differentiates between string literals and macros that have bytes
yielding alternatives.

Closes #3205

### CODE REVIEW

**Comment by yaahallo** [comment]
This is a WIP that doesn't work and I could use some help / mentoring on it. I moved the check in question to a new file because it seemed like failing an EarlyLintPass lint causes LateLintPass lints not to be run.

Also I'm not sure if im going about this entirely the wrong way. I expected to be able to use `ExprKind::Mac` to identify macros rather than string literals that precede a `as_bytes()` call, but all the macros seem to be expanded still even though its early_pass. I have a few things left to try still but I'm going to bed for now and thought I'd push what I've got. My current best guess is that I need to use something other than `check_expr` to get an actual pre macro check. Alternatively I'll probably look for other uses of `ExprKind::Mac` in the code base to see if I can't pinpoint where I'm messing up.

**Comment by yaahallo** [comment]
For what its worth, the debug traces that I added, which are included in this initial commit, produced the following output

```
error: MethodCall(PathSegment { ident: as_bytes#0, args: None }, [expr(9: "hello there")])

error: calling `as_bytes()` on a string literal
 --> tests/ui/strings_early.rs:6:14
  |
6 |     let bs = "hello there".as_bytes();
  |              ^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a byte string literal instead: `b"hello there"`
  |
  = note: `-D clippy::string-lit-as-bytes` implied by `-D warnings`

error: MethodCall(PathSegment { ident: as_bytes#0, args: None }, [expr(13: "☃")])

error: MethodCall(PathSegment { ident: as_bytes#0, args: None }, [expr(24: "foobar")])

error: calling `as_bytes()` on a string literal
  --> tests/ui/strings_early.rs:11:18
   |
11 |     let strify = stringify!(foobar).as_bytes();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a byte string literal instead: `bstringify!(foobar)`

error: MethodCall(PathSegment { ident: as_bytes#0, args: None }, [expr(25: "#![feature(tool_lints)]\n\n#![allow(unused, clippy::needless_
nsert_if_absent0<K: Eq + Hash, V>(m: &mut HashMap<K, V>, k: K, v: V) {\n    if !m.contains_key(&k) { m.insert(k, v); }\n}\n\nfn insert_if
absent2<K: Eq + Hash, V>(m: &mut HashMap<K, V>, k: K, v: V) {\n    if !m.contains_key(&k) { m.insert(k, v) } else { None };\n}\n\nfn inse
n insert_if_absent3<K: Eq + Hash, V>(m: &mut HashMap<K, V>, k: K, v: V) {\n    if !m.contains_key(&k) { foo(); m.insert(k, v) } else { No
 m.insert(k, v) };\n}\n\nfn insert_in_btreemap<K: Ord, V>(m: &mut BTreeMap<K, V>, k: K, v: V) {\n    if !m.contains_key(&k) { foo(); m.in
ns_key(&k) { m.insert(o, v); }\n}\n\nfn main() {\n}\n")])

error: calling `as_bytes()` on a string literal
  --> tests/ui/strings_early.rs:13:22
   |
13 |     let includestr = include_str!("entry.rs").as_bytes();
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a byte string literal instead: `binclude_str!("entry.r

error: aborting due to 7 previous errors


```

I was hoping the stringify or include_str would indicate that it was a macro :/

**Comment by flip1995** [comment]
`PreExpansionPass` lints have to be registered here:
https://github.com/rust-lang-nursery/rust-clippy/blob/1be78b90ac60e0416c0289d39093d5f811e8057b/clippy_lints/src/lib.rs#L200-L206
and not in the `register_plugins` function. Just move it there and the macros should not get expanded anymore.

`EarlyLintPass` lints will always suppress `LateLintPass` lints, it doesn't matter where you define them: rust-lang/rust#36161. You can leave this code in `strings.rs`.

File: clippy_lints/src/strings_early.rs [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+                } else if let ExprKind::Mac(ref mac) = args[0].node {
+                    if mac.node.path == "include_str" {
+                        cx.sess.err(&format!("{:?}", mac));
+                        span_lint_and_sugg(
+                            cx,
+                            STRING_LIT_AS_BYTES,
+                            e.span,
+                            "calling `as_bytes()` on a include_str macro",
+                            "consider using include_bytes instead",
+                            format!("include_str{}", snippet(cx, mac.span, "include_bytes")),
```
Comment (yaahallo) [inline clippy_lints/src/strings_early.rs]: This part is broken, I'm having trouble figuring out how to decompose the macro in order to swap out the include_str with include_bytes. Also I'm assuming that we shouldn't be recommending `bstringify!` instead of `stringify!` because I couldn't find any reference to such a macro in the documentation, so the intent here is to only lint for include_str -> include_bytes when its `macro!().as_bytes()`

**Comment by yaahallo** [comment]
re: moving it back to strings.rs. At the very least I think I'd still have to split up the strings.rs test case because there are still other late pass lints in there. What ended up happening was I moved the lint from late to early and it changed the number of lints in the stderr output from 11 to 2. Does it make more sense to have one `string.rs` clippy lint source file and two test case files or should I aim to keep it 1 to 1.

**Comment by flip1995** [comment]
Multiple test files are always better. We want to keep the size of the `*.stderr` files short. But for the code we want to keep things together, if they're doing similar things.

File: clippy_lints/src/strings_early.rs (hunk 1 above)
Comment (flip1995) [reply clippy_lints/src/strings_early.rs]: Yeah this should just trigger on the `include_str!` macro.

I think the arguments of the macro are in `mac.node.tts`. You should be able to format this with
```rust
format!("include_bytes!({})", mac.node.stream());
```
`mac.node.stream()` gives you a `TokenStream`, which implements the `Display` trait. [Documentation](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ast/struct.Mac_.html)

**Comment by yaahallo** [comment]
K I think we're getting close, I'm getting a strange failure on run-pass/used_underscore_binding_macro.rs. Also should I try to add `span_suggestion_with_applicability` to this lint?

File: clippy_lints/src/strings.rs [hunk 2]
```diff
@@ -143,12 +153,12 @@ impl LintPass for StringLitAsBytes {
     }
 }
 
-impl<'a, 'tcx> LateLintPass<'a, 'tcx> for StringLitAsBytes {
-    fn check_expr(&mut self, cx: &LateContext<'a, 'tcx>, e: &'tcx Expr) {
-        use crate::syntax::ast::LitKind;
+impl EarlyLintPass for StringLitAsBytes {
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, e: &crate::syntax::ast::Expr) {
```
Comment (yaahallo) [inline clippy_lints/src/strings.rs]: Is there a way to avoid having to use the full path here for Expr? It seemed like the Expr type for `LateLintPass` and `EarlyLintPass` are different, and this is the only way I could figure out to make them coexist.

Comment (flip1995) [reply clippy_lints/src/strings.rs]: Add `use crate::syntax::ast;` to the top of the file and just write `ast::Expr` here. Also below you could use `ast::LitKind`	and `ast::ExprKind`

The Expr type of `LateLintPass` is `hir::Expr`, because these lints operate on the HIR. `EarlyLintPass` lints operate on the AST so the Expr type is `ast::Expr`.

File: clippy_lints/src/strings.rs [hunk 3]
```diff
@@ -154,8 +155,8 @@ impl LintPass for StringLitAsBytes {
 }
 
 impl EarlyLintPass for StringLitAsBytes {
-    fn check_expr(&mut self, cx: &EarlyContext<'_>, e: &crate::syntax::ast::Expr) {
-        use crate::syntax::ast::{ExprKind, LitKind};
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, e: &ast::Expr) {
+        use self::ast::{ExprKind, LitKind};
```
Comment (yaahallo) [inline clippy_lints/src/strings.rs]: Why does this need the `self::`... path segment? is that what this is called? The type for `e` in the function args doesn't need it.

**Comment by mikerite** [comment]
I found that a big problem with pre-expansion lints is that they won't lint code "passed through" macros. 

Example:
```
use if_chain::if_chain;

fn main() {

    // Warns
    let _ = "test".as_bytes();

    if_chain! {
        if true;
        then {
            // Doesn't warn
            let _ = "test".as_bytes();
        }
    }
}
```
After this lint is changed to pre-expansion, it won't check inside the `if_chain! ` macro. It can't see into the macro because it hasn't been expanded. I think we need to be very careful about making anymore pre-expansion lints. Maybe we should even revisit the other lints we converted.

For fixing this bug, I found a possible alternative. In the original code, `snippet(cx, args[0].span.source_callsite(), "")` it will return the source before expansion. You can check if that string starts with "include_str!" when you create the suggestion.

File: clippy_lints/src/strings.rs (hunk 3 above)
Comment (flip1995) [reply clippy_lints/src/strings.rs]: The type in the function call just looks for the `use` statements of the file and can use them directly. `use`-statements on the other hand also need to be able to import stuff from outside the current file, so you have to specify where it should start looking. 
- Crate level: `crate::foo` in 2018 edition, `::foo` in 2015 edition
- Module level: `self::foo`
- Parent-module level: `super::foo` (parent-parent-module: `super::super::foo`, and so on)

If you just write `use foo` in the 2018 edition (`extern crate` got removed) it will look for a crate named `foo`, whereas `use self::foo` looks for a module/function/... inside the current module.

[Playground](https://play.rust-lang.org/?gist=2e2088dd2f9ef0ed61c610962b20eb3b&version=beta&mode=debug&edition=2018)

**Comment by flip1995** [comment]
Oh yeah, you're right, I never thought about that. The code inside the macro call isn't even parsed at the point where the `PreExpansionPass` lints get executed. We should limit `PreExpansionPass` to lints that **really** only look for a specific macro call.

~~Another option would be to split this up in an `EarlyLintPass` for the original lint and a `PreExpansionPass` for the `include_str` part.~~ But that would mean, that the same lint needs to be run twice. Thinking about it, I like the `source_callsite()` variant better.

@yaahallo Could you make this change? Sorry for the back and forth.

**Comment by yaahallo** [comment]
I'll take a look into using `source_callsite`.

File: clippy_lints/src/strings.rs [hunk 4]
```diff
@@ -152,7 +161,21 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for StringLitAsBytes {
             if path.ident.name == "as_bytes" {
                 if let ExprKind::Lit(ref lit) = args[0].node {
                     if let LitKind::Str(ref lit_content, _) = lit.node {
-                        if lit_content.as_str().chars().all(|c| c.is_ascii()) && !in_macro(args[0].span) {
+                        let callsite = snippet(cx, args[0].span.source_callsite(), "");
+                        let expanded = format!("\"{}\"", lit_content.as_str());
```
Comment (yaahallo) [inline clippy_lints/src/strings.rs]: I wasn't sure the best way to handle this, the content removes the quotation marks, I'm worried that this will break for raw strings when it shouldn't

File: clippy_lints/src/strings.rs [hunk 5]
```diff
@@ -152,7 +161,21 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for StringLitAsBytes {
...
+                        if callsite.starts_with("include_str!") {
+                            span_lint_and_sugg(
+                                cx,
+                                STRING_LIT_AS_BYTES,
+                                e.span,
+                                "calling `as_bytes()` on `include_str!(..)`",
+                                "consider using `include_bytes!(..)` instead",
+                                snippet(cx, args[0].span, r#""foo""#).replacen("include_str", "include_bytes", 1),
```
Comment (yaahallo) [inline clippy_lints/src/strings.rs]: Also not sure if this is the appropriate way to handle the replacement, I dont know how to destructure the callsite, Also, notably the output of line 164 and this are snippet function are the same, should I use arg[0].span rather than `callsite`?

I used replacen because I was afraid there may be other instances of "include_str" inside of the content of the span.

File: clippy_lints/src/strings.rs [hunk 6]
```diff
@@ -152,7 +161,21 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for StringLitAsBytes {
...
+                            );
+                        } else if callsite == expanded
```
Comment (yaahallo) [inline clippy_lints/src/strings.rs]: assumption is that otherwise the expanded and original text must be the same for it to recommend a `b`

File: tests/ui/strings.rs [hunk 7]
```diff
@@ -53,6 +53,8 @@ fn str_lit_as_bytes() {
     let ubs = "☃".as_bytes();
 
     let strify = stringify!(foobar).as_bytes();
```
Comment (yaahallo) [inline tests/ui/strings.rs]: This on longer produces a lint, I think this is what we want.

**Comment by yaahallo** [comment]
Also, I'm sorry this took so long :/ I had it mostly ready and just never set aside the time to finish the last 5% and push it.

**Comment by flip1995** [comment]
> Also, I'm sorry this took so long :/ I had it mostly ready and just never set aside the time to finish the last 5% and push it.

No problem, we've all been there :D 

I'll try to take a closer look at this in the next two days.

File: clippy_lints/src/strings.rs (hunk 4 above)
Comment (flip1995) [reply clippy_lints/src/strings.rs]: Could you add a test for raw strings, then we'll see how to handle them.

File: clippy_lints/src/strings.rs (hunk 5 above)
Comment (flip1995) [reply clippy_lints/src/strings.rs]: I would replace the snippet function with `callsite`, to avoid building the snippet twice. But the default value of the `callsite` should be adapted to not just be an empty string. (either keep `r#""foo""#` or at least `r#""""#`)

The `replacen` seems good to me.

File: tests/ui/strings.rs [hunk 8]
```diff
@@ -62,6 +64,6 @@ fn main() {
 
     // the add is only caught for `String`
     let mut x = 1;
-    ; x = x + 1;
+;    x = x + 1;
```
Comment (flip1995) [inline tests/ui/strings.rs]: Why is this semicolon even there? Could you remove it please?

File: tests/ui/strings.stderr [hunk 9]
```diff
@@ -60,17 +60,17 @@ error: calling `as_bytes()` on a string literal
...
-  --> $DIR/strings.rs:55:18
+error: calling `as_bytes()` on `include_str!(..)`
+  --> $DIR/strings.rs:57:22
    |
-55 |     let strify = stringify!(foobar).as_bytes();
-   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a byte string literal instead: `bstringify!(foobar)`
+57 |     let includestr = include_str!("entry.rs").as_bytes();
+   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `include_bytes!(..)` instead: `include_bytes!("entry.rs")`
 
 error: manual implementation of an assign operation
```
Comment (flip1995) [inline tests/ui/strings.stderr]: Can you add an `#[allow(clippy::assign_op_pattern)]` to suppress this lint. That's not the intent of these lines.

(Not really part of this PR, but imaginary bonus points for you! :tada: )

**Comment by flip1995** [comment]
Now I'm sorry this took so long :/ I took last week off and couldn't look over this last weekend.

Everything except the 4 comments I left LGTM

(Needs a rebase)

File: clippy_lints/src/strings.rs (hunk 4 above)
Comment (yaahallo) [reply clippy_lints/src/strings.rs]: It doesn't lint the raw strings at all as currently written because the poor reproduction of the expanded lit doesn't satisfy the first expression in the else if `callsite == expanded`.

I'm gonna try to inspect the members of ExprKind and LitKind to see if I can find some place that stores the terminators or w/e they're called for the raw string. Otherwise I can also just search the callsite for an `r(.*)"` type pattern and reuse that when constructing the expanded literal.

Comment (flip1995) [reply clippy_lints/src/strings.rs]: `LitKind::Str` has as second parameter the `StrStyle`. If it is a `StrStyle::Raw(u16)`, the `u16` will tell you how many `#` were used. I hope this helps. [Docs](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ast/enum.StrStyle.html#variant.Raw)

Comment (yaahallo) [reply clippy_lints/src/strings.rs]: Variants `Cooked` and `Raw`, beast. This is perfect ty for the heads up.

**Comment by phansch** [comment]
looks good to me, too!

bors r+
