### PR TITLE
Simplify manual_memcpy suggestion in some cases

### LINKED ISSUE #3004: Misleading manual_memcpy suggestion
Following code:
```rust
fn copy(arr: &mut [u8], from: usize, target: &[u8]) {
    for i in from..from + target.len() {
        arr[i] = target[i - from];
    }
}
```
triggers this warning:
```rust
warning: it looks like you're manually copying between slices
 --> src/main.rs:2:14
  |
2 |     for i in from..from + target.len() {
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try replacing the loop by: `arr[from..from + target.len()].clone_from_slice(&target[(from - from)..(from + target.len() - from)])`
  |
  = note: #[warn(manual_memcpy)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#manual_memcpy
```
But this contains `(from - from)`, which by itself leads to next error:
```rust
error: equal expressions as operands to `-`
 --> src/main.rs:3:35
  |
3 |         .clone_from_slice(&target[(from - from)..(from + target.len() - from)])
  |                                   ^^^^^^^^^^^^^
  |
  = note: #[deny(eq_op)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#eq_op
```
In the case of copying the entire slice `clippy` may provide specialized  suggestion
```rust
warning: it looks like you're manually copying between slices
 --> src/main.rs:2:14
  |
2 |     for i in from..from + target.len() {
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try replacing the loop by: `arr[from..from + target.len()].clone_from_slice(&target)`
  |
```

### PR DESCRIPTION
**Pull request by pengowen123**
Checking whether the entire source slice is copied is difficult, but this should catch common cases.
Fixes #3004

### CODE REVIEW

File: clippy_lints/src/loops.rs [hunk 1]
```diff
@@ -972,15 +984,41 @@ fn detect_manual_memcpy<'a, 'tcx>(
...
 
+                let mut end_expr = end;
+                let mut reduced_end_expr = false;
+
+                if_chain! {
+                    if let ExprKind::Binary(ref op, ref left, ref right) = end.node;
+                    if let BinOpKind::Add = op.node;
+                    then {
+                        if let Some(left) = sugg::Sugg::hir_opt(cx, left) {
+                            if left.to_string() == offset.value {
```
Comment (oli-obk) [inline clippy_lints/src/loops.rs]: I'm not too happy about the `to_string()` + comparison.

The other changes in this PR are great, but I'd prefer to postpone this entire `if_chain` until we have a proper expression minifier/optimizer

File: tests/ui/for_loop.rs [hunk 2]
```diff
@@ -550,6 +550,15 @@ pub fn manual_copy(src: &[i32], dst: &mut [i32], dst2: &mut [i32]) {
     for i in 0..10 {
         dst_vec[i] = src[i];
     }
+
+    // Copying entire source slice - simplify suggestion (issue #3004)
+    let src = [0, 1, 2, 3, 4];
+    let mut dst = [0, 0, 0, 0, 0, 0];
+    let from = 1;
+
+    for i in from..from + src.len() {
```
Comment (oli-obk) [inline tests/ui/for_loop.rs]: Please also add a test for values other than `src.len()`. I think your PR will also improve the suggestion in that case

File: clippy_lints/src/loops.rs (hunk 1 above)
Comment (pengowen123) [reply clippy_lints/src/loops.rs]: I removed it, but this makes the `0..src.len()` check below useless until the expression minifier is implemented. Should I remove that as well?

Comment (oli-obk) [reply clippy_lints/src/loops.rs]: Oh... I guess, no need to keep around currently dead code

**Comment by pengowen123** [comment]
@oli-obk Sorry, I forgot to notify you that I removed the dead code. The PR should be good to go unless you have more comments.

**Comment by oli-obk** [comment]
Thanks!
